# 개발용 yml
version: "3.6"
services:
  clb1:
    restart: always
    build: .
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - CLEANERBOT_TOKEN=${CLEANERBOT_TOKEN}
    volumes:
      - .:/code
    ports:
      - "8087:8087"
      - "8086:8086"
      - "8085:8085"